'use client'
import Header from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="dukAURC92eiPKRoQMAKTdRxHZJ-l0Yw79O5jyHW47do" />
      <body className={inter.className}>
        <Navigation/>
        <Header />
        <main>{children}</main>
        </body>
    </html>
  )
}
